BulkyWeb/Areas/Admin/Controllers/CompanyController.cs
using Bulky.DataAccess.Data;
using Bulky.DataAccess.Repository;
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models.Models;
using Bulky.Models.ViewModel;
using Bulky.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory.Database;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")] //Specify The Area Of Controller Because its neccesiary to Define The Routing As Admin for this Controller
    [Authorize(Roles=SD.Role_User_Admin)]
    public class CompanyController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _db;
        private readonly IWebHostEnvironment _environment;

        public CompanyController(ApplicationDbContext db, IWebHostEnvironment webhostenviroment, IUnitOfWork unitOfWork)
        {
            _db = db;
            _environment = webhostenviroment;
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            // Convert IEnumerable<Company> to List<Company>
            List<Company> Companys = _unitOfWork.Company.GetAll().ToList();

            return View(Companys);
        }

        public IActionResult Upsert(int? id)
        {
            // Create the CompanyVM object with an empty Company and CategoryList
            Company Company = new Company();

            // Pass the CompanyVM object to the view
            if (id == null || id == 0)
            {
                return View(Company);
            }
            else
            {
                Company = _db.Company.Find(id);
                return View(Company);
            }

        }

        [HttpPost] // Specifies that this action will handle HTTP POST requests
        public IActionResult Upsert(Company company)
        {
            // Check if the Company title is null and add a validation error if true
            if (company.Name == null)
            {
                ModelState.AddModelError("Name", "The Name Cannot Be Empty");
            }

          

                // Add the Company to the database and save changes

                if (company.Id == 0)
                {
                    _db.Company.Add(company);
                }
                else
                {
                    _db.Company.Update(company);
                }

                _db.SaveChanges();

                // Redirect to the Index page after saving the Company
                return RedirectToAction("Index");

            return View(company);
            }






        [HttpPost]

        public IActionResult Edit(Company Company)
        {

            if (ModelState.IsValid)
            {
                _db.Company.Update(Company);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(Company);
        }

        #region Api Calls
        [HttpGet]
        public IActionResult GetAll()
        {
            var Companys = _unitOfWork.Company.GetAll()
                                              .Select(p => new {
                                                  p.Id,
                                                  p.Name,
                                                  p.StreetAdress,
                                                  p.City,
                                                  p.State,
                                                  p.PostalCode,
                                                  p.PhoneNumber,
                                                  
                                              }).ToList();

            return Json(new { data = Companys });
        }

        //[HttpDelete]

        public IActionResult Delete(int? id)
        {
            // Check if the id is null
            if (id == null)
            {
                return Json(new { success = false, message = "Invalid Company ID" });
            }

            // Fetch the Company to be deleted
            var CompanyToBeDeleted = _unitOfWork.Company.Get(u => u.Id == id);

            if (CompanyToBeDeleted == null)
            {
                return Json(new { success = false, message = "Company not found" });
            }

           

            // Remove the Company from the database
            _unitOfWork.Company.Remove(CompanyToBeDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Company successfully deleted" });
        }



        #endregion

    }
}

BulkyWeb/Areas/Admin/Controllers/OrderController.cs
using Bulky.DataAccess.Repository.IRepository;
using Bulky.Models.Models;
using Bulky.Models.ViewModel;
using Bulky.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BulkyWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class OrderController : Controller
    {
     
        private readonly IUnitOfWork _unitOfWork;
        [BindProperty]
        public OrderVM orderVm { get; set; }
    
        public OrderController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;   
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Details(int orderId)
        {
            orderVm = new()
            {
                orderHeader = _unitOfWork.OrderHeader.Get(u => u.Id == orderId, includeProperties: "ApplicationUser"),
                orderDetails = _unitOfWork.OrderDetails.GetAll(u => u.orderHeader.Id == orderId, includeProperties: "Product")
            };
            return View(orderVm);
        }

        [HttpPost]
        [Authorize(Roles = SD.Role_User_Admin + "," + SD.Role_User_Employee)]

        public IActionResult UpdateOrderDetails()
        {
            var orderHeaderFromDb = _unitOfWork.OrderHeader.Get(u => u.Id == orderVm.orderHeader.Id);

            orderHeaderFromDb.Name = orderVm.orderHeader.Name;
            orderHeaderFromDb.PhoneNumber = orderVm.orderHeader.PhoneNumber;
            orderHeaderFromDb.StreetAdress = orderVm.orderHeader.StreetAdress;
            orderHeaderFromDb.City = orderVm.orderHeader.City;
            orderHeaderFromDb.PostalCode = orderVm.orderHeader.PostalCode;

            if (!string.IsNullOrEmpty(orderVm.orderHeader.TrackingNumber))
            {
                orderHeaderFromDb.TrackingNumber = orderVm.orderHeader.TrackingNumber;
            }
            if (!string.IsNullOrEmpty(orderVm.orderHeader.Carrier))
            {
                orderHeaderFromDb.Carrier = orderVm.orderHeader.Carrier;
            }
            _unitOfWork.OrderHeader.Update(orderHeaderFromDb);
            _unitOfWork.Save();
            TempData["Success"] = "Order Details Updated Succesfully";

            return RedirectToAction(nameof(Details),new  { orderId=orderHeaderFromDb.Id});
        }



        [HttpGet]
       public IActionResult GetAll(string status)
        {
            IEnumerable<OrderHeader> orderHeaders;

            if (User.IsInRole(SD.Role_User_Admin)|| User.IsInRole(SD.Role_User_Employee))
            {
                orderHeaders= _unitOfWork.OrderHeader.GetAll(includeProperties: "ApplicationUser").ToList();
            }
            else
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier).Value;

                orderHeaders=_unitOfWork.OrderHeader.GetAll(u=>u.ApplicationUserId==userId,includeProperties:"ApplicationUser");
            }


            switch (status)
            {
                case "pending":
                    orderHeaders = orderHeaders.Where(u => u.PaymentStatus == SD.PaymentStatusDeleayedPayment);
                    break;
                case "inprocess":
                    orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.StatusInProcess);
                    break;
                case "completed":
                    orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.StatisShipped);
                    break;
                case "approved":
                    orderHeaders = orderHeaders.Where(u => u.OrderStatus == SD.StatusApproved);
                    break;
                deafult:
                    break;
            }


            return Json(new { data = orderHeaders });
        }
        

    }
}

BulkyWeb/Controllers/CategoryController.cs
using Bulky.DataAccess.Data;
using Bulky.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Collections.Generic;  // Make sure to include this

namespace BulkyWeb.Controllers
{
    public class CategoryController : Controller  // Inherited from Controller
    {
        private readonly ApplicationDbContext _db;  // Access field for storing the Database Context

        // Constructor to inject the DbContext into the controller
        public CategoryController(ApplicationDbContext db)
        {
            _db = db;  // Store the DbContext in a private field
        }

        // Action method to handle the Index view and return a list of categories
        public IActionResult Index()//IActionResult is the base type for all the result types in ASP.NET Core MVC. 
        {
            // Fetch the categories from the database (using the correct 'Categories' property)
            List<Category> categoryList = _db.categories.ToList();

            // Pass the categories to the view
            return View(categoryList);
        }

        public IActionResult Create()//Action Controller To Create And Direct to the Create Page
        {
            return View();
        }
        [HttpPost] //The Same Controller Is Making A Post Request Where in The Ui is submiting a form
        public IActionResult Create(Category modelTypeCat)//Type of Category Model createing an Object from Form
        {
            if (modelTypeCat.Name == modelTypeCat.CategoryOrder.ToString())
            {
                ModelState.AddModelError("Name", "The DisplayOrder Cannot be the same as Name");
            }

            if (ModelState.IsValid)//Catching Erros
            {
                _db.Add(modelTypeCat);//Adding the form Inputs to Db
                _db.SaveChanges();//Saving 
                TempData["Success"] = "Created Succesful Data";
                return RedirectToAction("Index");//Redirects to Dashboard where we are displaying data from database
            }


            return View();//If Error it Redirects to Same Page
        }

        public IActionResult Edit(int? id) //Initialize an Integer to match id of View
        {
            if (id == null || id == 0)//Catch Errors
            {
                return NotFound();
            }

            Category editedItem = _db.categories.Find(id); //Find Id In Database
            //Category editedItem2 = _db.categories.FirstOrDefault(u => u.Id == id);
            //Category editedItem1 = _db.categories.Where(n => n.Id == id).FirstOrDefault();
            if (editedItem.Id == null || editedItem.Id == 0)
            {
                return NotFound();
            }
            return View(editedItem); //Return The Found Column Category
        }

        [HttpPost]
        public IActionResult Edit(Category obj)//Post For the Same Acition Edit To Update
        {
            if (ModelState.IsValid)//If Model Is Correct
            {
                _db.categories.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id) 
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Category findDeletion = _db.categories.Find(id);

            if (findDeletion.Id == null || findDeletion.Id == 0)
            {
                return NotFound();
            }

            return View(findDeletion);
        }

        [HttpPost,ActionName("Delete")] //The Delete Post is Called with Delete Action naming
        public IActionResult DeletePost(Category obj)
        {

            _db.categories.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            
            return View(obj);
        }

            
        }
    }

BulkyWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor HttpContextAccessor


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/2.1.8/css/dataTables.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BulkyWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a> <!--Define Area-->
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>  <!--Define Area-->
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>  <!--Define Area-->
                        </li>
                        
                            @if(User.IsInRole(SD.Role_User_Admin))
                            {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Dropdown
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Order" asp-action="Index">Orders</a>
                                    </li>
                                    <li><hr class="dropdown-divider"></li>
                                </ul>
                            </li>
                            }
                        @if (HttpContextAccessor.HttpContext.Session.GetInt32(SD.sessionCart) != null)
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    <i class="bi bi-cart">
                                        @(HttpContextAccessor.HttpContext.Session.GetInt32(SD.sessionCart))
                                    </i>
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                    <i class="bi bi-cart">(0)</i>
                                </a>
                            </li>
                        }
                       


                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" /> <!--Created a Partial View With Toasr Errors And Success Based on TempData[]-->
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark text-light text-muted">
        <div class="container">
            &copy; 2024 -Made With<i class="bi bi-balloon-heart-fill-light"></i> BulkyWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/2.1.8/js/dataTables.min.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)


</body>
</html>

BulkyWeb/Views/Shared/_Notification.cshtml
@{
            // Only load the Toastr and jQuery libraries once
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
}

<script>
    // Display Toastr success message if TempData["Success"] is not null
    @if (TempData["Success"] != null)
    {
        <text>
                toastr.success('@TempData["Success"]');
        </text>
    }

        // Display Toastr error message if TempData["Error"] is not null
    @if (TempData["Error"] != null)
    {
        <text>
                toastr.error('@TempData["Error"]');
        </text>
    }
</script>